import { supabase } from './supabase';

interface SubmitReportParams {
  imageBase64: string;
  latitude: string;
  longitude: string;
  notes?: string;
  // These are now optional - will be generated by AI if not provided
  wasteType?: 'organik' | 'anorganik' | 'berbahaya' | 'campuran';
  wasteVolume?: 'kurang_dari_1kg' | '1_5kg' | '6_10kg' | 'lebih_dari_10kg';
  locationCategory?: 'sungai' | 'pinggir_jalan' | 'area_publik' | 'tanah_kosong' | 'lainnya';
}

interface SubmitReportResponse {
  success: boolean;
  message?: string;
  data?: {
    report_id: number;
    image_url: string;
    validation: {
      isWaste: boolean;
      confidence: string;
      reason?: string;
      waste_type?: 'organik' | 'anorganik' | 'berbahaya' | 'campuran';
      waste_volume?: 'kurang_dari_1kg' | '1_5kg' | '6_10kg' | 'lebih_dari_10kg';
      location_category?: 'sungai' | 'pinggir_jalan' | 'area_publik' | 'tanah_kosong' | 'lainnya';
    };
    created_at: string;
  };
  error?: string;
  validation?: {
    isWaste: boolean;
    confidence: string;
    reason?: string;
    waste_type?: 'organik' | 'anorganik' | 'berbahaya' | 'campuran';
    waste_volume?: 'kurang_dari_1kg' | '1_5kg' | '6_10kg' | 'lebih_dari_10kg';
    location_category?: 'sungai' | 'pinggir_jalan' | 'area_publik' | 'tanah_kosong' | 'lainnya';
  };
}

export async function submitReport(params: SubmitReportParams): Promise<SubmitReportResponse> {
  try {
    // Get the session token
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) {
      throw new Error('No active session. Please login first.');
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    if (!supabaseUrl) {
      throw new Error('Missing Supabase URL configuration');
    }

    // Call the edge function
    const response = await fetch(
      `${supabaseUrl}/functions/v1/submit-report`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${session.access_token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          image_base64: params.imageBase64,
          lattitude: params.latitude,
          longitude: params.longitude,
          notes: params.notes || '',
          // Only send these if provided (optional for AI-generated data)
          ...(params.wasteType && { waste_type: params.wasteType }),
          ...(params.wasteVolume && { waste_volume: params.wasteVolume }),
          ...(params.locationCategory && { location_category: params.locationCategory }),
        }),
      }
    );

    
    const responseText = await response.text();
    
    let data: SubmitReportResponse;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      console.error('Failed to parse response:', e);
      throw new Error(`Server returned invalid JSON: ${responseText.substring(0, 200)}`);
    }
    
    if (!response.ok) {
      return data;
    }

    return data;
  } catch (error) {
    console.error('Error submitting report:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

/**
 * Convert a file to base64 string
 */
export function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
        const base64 = reader.result.split(',')[1];
        resolve(base64);
      } else {
        reject(new Error('Failed to convert file to base64'));
      }
    };
    reader.onerror = (error) => reject(error);
  });
}

/**
 * Resize and compress image before upload
 */
export function resizeImage(file: File, maxWidth: number = 1024, maxHeight: number = 1024): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = (event) => {
      const img = new Image();
      img.src = event.target?.result as string;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        let width = img.width;
        let height = img.height;

        // Calculate new dimensions
        if (width > height) {
          if (width > maxWidth) {
            height *= maxWidth / width;
            width = maxWidth;
          }
        } else {
          if (height > maxHeight) {
            width *= maxHeight / height;
            height = maxHeight;
          }
        }

        canvas.width = width;
        canvas.height = height;

        const ctx = canvas.getContext('2d');
        ctx?.drawImage(img, 0, 0, width, height);

        // Convert to base64 with compression
        const base64 = canvas.toDataURL('image/jpeg', 0.8).split(',')[1];
        resolve(base64);
      };
      img.onerror = reject;
    };
    reader.onerror = reject;
  });
}
